# ç›¸å…³é…ç½®è¯´æ˜
  # favicon: ç½‘ç«™å›¾æ ‡
  # avatar: ä¸»é¢˜ç”¨æˆ·å¤´åƒä¸æ˜µç§°
  # rss: rssè®¢é˜…
  # gtag: Google åˆ†æ
  # comments: æ–‡ç« è¯„è®ºç³»ç»Ÿ
    # gitalk
    # disqus
  # navbar: ä¸»é¢˜é¡µé¢å¯¼èˆªæ 
  # catalog: æ–‡ç« ç›®å½•
  # prevnext: æ–‡ç« æœ«å°¾çš„ä¸Šä¸€é¡µä¸ä¸‹ä¸€é¡µ
  # friends: å‹é“¾
  # footer: é¡µè„šä¿¡æ¯
  # search: æ–‡ç« æœç´¢
  # colorSwitch: æ·±/æµ…é…è‰²åˆ‡æ¢
  # postShare: æ–‡ç« åˆ†äº«
  # codeBlock: ä»£ç å—é…ç½®

# enable: æ˜¯å¦å¼€å¯ç›¸åº”åŠŸèƒ½ï¼Œå¯é€‰true || false

# ç½‘ç«™å›¾æ ‡
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: https://s2.loli.net/2022/01/23/ZxVkEM5sdLQ7phN.jpg #/images/favicon.png

# ç”¨æˆ·å¤´åƒä¸æ˜µç§°
avatar:
  author_photo: https://s2.loli.net/2022/01/23/ZxVkEM5sdLQ7phN.jpg #/images/avatar.png https://s2.loli.net/2022/03/27/gFT9G13m6sdUMke.jpg
  author_nickname: XwX
  path: /

# Google åˆ†æ
# https://analytics.google.com
# æ³¨å†ŒGoogleåˆ†æè´¦å·ï¼Œåœ¨ç®¡ç†/åˆ›å»ºåª’ä½“èµ„æº/é€‰æ‹©ç½‘ç«™/å¡«å†™ç›¸å…³ä¿¡æ¯åå¾—åˆ°è·Ÿè¸ªIdï¼Œä¸€èˆ¬æ ¼å¼ä¸ºUA-xxxxxxx-x
# å¦‚ä¹‹å‰å·²æœ‰æ³¨å†Œè´¦å·ï¼Œåœ¨ç®¡ç†/è·Ÿè¸ªä¿¡æ¯/è·Ÿè¸ªä»£ç /æ‰¾åˆ°è·Ÿè¸ªIDï¼Œä¸€èˆ¬æ ¼å¼ä¸ºUA-xxxxxxx-x
gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

# æ–‡ç« è¯„è®ºç³»ç»Ÿ
comments:
  enable: true
  # ç›®å‰ä»…æ”¯æŒgitalk, valine, disqusè¯„è®ºï¼Œé€‰æ‹©å–œæ¬¢çš„ä¸€ç§å¼€å¯å³å¯

  gitalk:
    # https://github.com/gitalk/gitalk#usageæŸ¥çœ‹å®˜æ–¹æ•™ç¨‹
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # è¿›å…¥ä»¥ä¸Šç½‘å€æŸ¥çœ‹å®˜æ–¹æ•™ç¨‹
    enable: true
    appId: YBH7dy8YlNz0JsvUT2vw1rVn-MdYXbMMI
    appKey: Q7qAfgOW7OkXlWMWf62B4lb2
    placeholder: WhatEver!
    avatar: retro
    vempty_display: true

  # disqus éœ€ç§‘å­¦ä¸Šç½‘æ–¹å¯ä½¿ç”¨
  disqus:
    # https://disqus.com/
    # æ³¨å†Œè´¦å·ï¼Œè·å–shortname.disqus.comï¼Œshortnameä¸ºä½ å®šä¹‰çš„å”¯ä¸€name
    # ä¾‹ï¼šæˆ‘æ³¨å†Œé…ç½®å®Œæ¯•åçš„ç½‘å€ä¸ºzxcxxxx.disqus.comï¼Œhttps-zxcxxxx-github-ioå³ä¸ºshortname
    enable: false
    shortname: https-zxcxxxx-github-io
  
  # waline https://waline.js.org
  waline:
    enable: false
    serverURL:

# ä¸»é¢˜é¡µé¢å¯¼èˆªæ 
navbar:
  -
    name: ä¸»é¡µ
    enable: true
    path: /
    key: home
  -
    name: å½’æ¡£
    enable: false
    path: /archives/
    key: archives
  -
    name: åˆ†ç±»
    enable: false
    path: /categories/
    key: categories
  -
    name: æ ‡ç­¾
    enable: false
    path: /tags/
    key: tags
  -
    name: ä¸€è¨€
    enable: false
    path: /artitalk/
    key: hitokoto
  -
    name: ä¸€è¨€
    enable: true
    path: /shuoshuo/
    key: hitokoto
  -
    name: ğŸŸ
    enable: true
    path: /sakana/
    key: sakana
  -
    name: åª’ä½“
    enable: true
    path: /media/
    key: media
  -
    name: æ–°ç•ª
    enable: true
    path: /bangumi/
    key: bangumi
  -
    name: é“¾æ¥
    enable: true
    path: /link/
    key: link
  -
    name: å…³äº
    enable: true
    path: /about/
    key: about

# æ–‡ç« ç›®å½•
catalog:
  enable: true

# æ–‡ç« æœ«å°¾çš„ä¸Šä¸€é¡µä¸ä¸‹ä¸€é¡µ
prevnext:
  enable: true

# å‹é“¾è¯¦ç»†ä¿¡æ¯ï¼šæ”¯æŒå¤šä¸ªå‹é“¾
friends:
  # nickname: æ˜µç§°
  # site: åœ°å€
  # meta: æè¿°
  -
    nickname: Hexo
    site: https://hexo.io/
    meta: 'Powered by.'
  -
    nickname: Zcheng
    site: https://hexo.theme.oranges.zcheng.site/
    meta: 'The theme.'
  -
    nickname: qiankanshan
    site: https://qiankanshan.com/
    meta: 'Future Musician.'
  -
    nickname: zhijiao
    site: http://zhijiao-blog.com/
    meta: 'shark.'
  -
    nickname: mdnd
    site: https://mdnd.top/
    meta: 'mdnd.'

# é¡µè„šä¿¡æ¯
footer:
  # social: ç¤¾äº¤æ–¹å¼
  # more: æ›´å¤šé¡µè„šä¿¡æ¯
  social:
    # name: åç§°
    # icon: å›¾æ ‡ï¼Œç›®å‰ä»…æ”¯æŒIconFontéƒ¨åˆ†å›¾æ ‡
    # path: åœ°å€
    -
      name: github
      icon: github
      path: https://github.com/XwX12596/blog-oranges
    -
      name: email
      icon: envelope
      path: mailto:1259685860@qq.com
    # -
    #   name: twitter
    #   icon: twitter
    #   path:
    # -
    #   name: wechat
    #   icon: wechat
    #   path:
    -
      # rsséœ€å®‰è£… hexo-generator-feed æ’ä»¶
      # å…·ä½“å‚ç…§https://github.com/hexojs/hexo-generator-feed
      name: rss
      icon: rss
      path: /atom.xml

  more:
    # æ”¯æŒå˜é‡æ˜¾ç¤ºï¼Œå¯è‡ªå®šä¹‰æ‰©å±•ï¼Œå…·ä½“è§ä¸»é¢˜/layout/_partial/footer.ejs
    # ä¸€èˆ¬ç”¨æ¥æ˜¾ç¤ºæ ¹æ®å„ç§åœºæ™¯éœ€è¦åˆ‡æ¢çš„æ–‡æœ¬ï¼Œå¦‚æ—¶é—´å¹´ä»½
    # å¦‚ï¼š{thisYear} ä¼šè¢«æ›¿æ¢ä¸ºä»Šå¹´å¹´ä»½
    -
      name: è‹ICPå¤‡2022006233å·
      path: https://beian.miit.gov.cn/
    -
      name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges

  # æµè§ˆé‡ç»Ÿè®¡
  # http://busuanzi.ibruce.info/
  views:
    enable: true
    provider: '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
    item:
      -
        enable: true
        id: busuanzi_value_site_pv
        name: æœ¬ç«™æ€»è®¿é—®é‡
        unit: æ¬¡
      -
        enable: true
        id: busuanzi_value_page_pv
        name: æœ¬æ–‡æ€»é˜…è¯»é‡
        unit: æ¬¡
      -
        enable: true
        id: busuanzi_value_site_uv
        name: æœ¬ç«™è®¿å®¢æ•°
        unit: äºº

# æ–‡ç« æœç´¢
search:
  enable: true
  placeholder: 'æœç´¢'

# æ·±/æµ…é…è‰²åˆ‡æ¢
colorSwitch:
  enable: true

# æ–‡ç« åˆ†äº«
postShare:
  enable: true

  twitter:
    enable: true

  facebook:
    enable: true

# ä»£ç å—é…ç½®
codeBlock:
  # ä»£ç å—é£æ ¼ï¼Œé»˜è®¤normal
  # å¯é€‰ï¼šé»˜è®¤é£æ ¼'normal'ï¼›macé»‘è‰²é£æ ¼ï¼š'mac-black'
  style: 'mac-black'
  # ä»£ç å¤åˆ¶
  copy:
    enable: true

# MathJax Support
# æ•°å­¦å…¬å¼æ”¯æŒ
mathjax:
  enable: true

# cdné…ç½®ï¼Œé»˜è®¤å…³é—­ï¼Œå¦‚éœ€å¯åŠ¨ï¼Œå…ˆç¡®ä¿å¯¹åº”æ’ä»¶ç‰ˆæœ¬cdnèµ„æºå¯ç”¨åå†å¼€å¯
# å¦‚èµ„æºåŠ è½½å¤±è´¥ï¼Œå¯æ›¿æ¢cdnæä¾›å•†æˆ–è®¾ç½®enable:falseé»˜è®¤èµ°æœ¬åœ°èµ„æº
# ä¹Ÿå¯ä½¿ç”¨è‡ªå·±çš„cdnæœåŠ¡ï¼Œèµ„æºåœ¨/theme/oranges/source/pluginsä¸‹
cdns:
  jquery:
    enable: false
    url: https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js

  fancybox:
    enable: false
    url:
      css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
      js: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  # LaTeX å…¬å¼
  mathjax:
    enable: true
    url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

  # ä»£ç å—å¤åˆ¶
  clipboard:
    enable: false
    url: https://cdn.jsdelivr.net/npm/clipboard@2.0.10/dist/clipboard.min.js

  # è¯„è®ºç³»ç»Ÿ
  comments:
    gitalk:
      enable: false
      url:
        css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
        js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

    valine:
      enable: true
      url: https://cdn.jsdelivr.net/npm/valine@1.4.18/dist/Valine.min.js

    waline:
      enable: false
      url: https://cdn.jsdelivr.net/npm/@waline/client@2.5.1/dist/legacy.min.js

# ä¸»é¢˜è‰²
themeColor: '#808080'
